name: deploy-app
on:
    push:
        branches:
            - "master"
        # paths:
        #     - "src"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Execute Server Command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AIRI_SSH_HOST }}
                  username: ${{ secrets.AIRI_SSH_USER }}
                  key: ${{ secrets.AIRI_SSH_PRIVATE_KEY }}
                  script: |
                      echo "SSH into the server"
                      docker stop izuna-runtime
                      sleep 10
                      docker container rm izuna-runtime
                      docker image prune -f
                      rm -rf izuna
                      git clone https://github.com/genshiken/sugar-bot.git
                      cd izuna
                      docker build . -t izuna:latest
                      cd ..
                      rm -rf izuna
                      docker run -d -p 8000:8000 --name izuna-runtime --network=closure-network \
                      -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
                      -e SUGARBOORU_API_KEY=${{ secrets.SUGAR_SUGARBOORU_API_KEY }} \
                      -e DATABASE_URL=${{ secrets.SUGAR_DB_URL }} izuna:latest
